server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: productService
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**
          filters:
            - name: JwtAuthenticationFilter


logging:
  level:
    org.springframework.cloud.gateway: DEBUG



